services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: taskmanager
      POSTGRES_USER: taskuser
      POSTGRES_PASSWORD: taskpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: ./backend
    volumes:
      - .backend/:/app
    working_dir: /app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://taskuser:taskpass@db:5432/taskmanager
    ports:
      - "8000:8000"

volumes:
  postgres_data: